# Generated by Django 4.2.3 on 2023-09-08 08:49

from django.db import migrations, models
import requests.sessions


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_alter_product_created'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=requests.sessions.Session, to='cart.cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=requests.sessions.Session, to='ecomapp.product'),
        ),
    ]
