# Generated by Django 4.1.6 on 2023-02-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turf',
            fields=[
                ('turf_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turf_name', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('turf_image', models.ImageField(upload_to='static/image')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('turf_size', models.CharField(max_length=40)),
            ],
        ),
    ]
